<!--date=20080101 -->
<?php include("../../headercat.php"); ?>

<h1>Basic Concepts of Electricity</h1>

<p>Matter is the substance that forms all physical things. Matter can be defined as anything that has mass and occupies space. Matter appears predominately as atoms. The three physical states of matter are solid, liquid and gas. The three chemical states of matter are elements, compounds and mixtures. An element is a substance that cannot be broken down into a smaller substance. A compound is a chemical reaction from the combination of two or more elements to. A mixture is a combination of two or more elements where the elements retain the same properties as when they are alone. No chemical change occurs.</p>
<p>Although science has identified other particles of the atom, the parts of the atom that are of interest to Electronics Technicians are the Proton, Neutron and Electron. Protons have a positive electrical charge and are located in the nucleus of the atom, along with the neutron. Electrons have a negative electrical charge and orbit the nucleus of the atom at trillions of times a second. Electrons are approximately 9×10 to the -28th power in weight, and are around 1800 times lighter than protons. Atoms contain an equal amount of protons and electrons. The number of protons in a single atom of an element is known as the Atomic Number. This number is usually shown on a Periodic Table of Elements.</p>
<p>Electrons orbitting around the nucleus of an atom align themselves in a stuctured manner known as shells. The first ring or shell contains up to two electrons. The second shell contains up to 8 electrons. The third shell contains up to 18 electrons. The outermost or valence shell, can never contain more than 8 electrons. The number of valence electrons determines it’s stability or instability, both electrically and chemically. The valence shell is full when it contains 8 electrons. Electrically, these outer electrons can be easily moved and are also referred to as free electrons.</p>
<p>When an electron leaves it’s original atom, it leave behind an atom that is no longer neutrally charged. This is called an Ion. With this example, since the electrons are negatively charged, the absence of it creates a positively charged ion. When the valence shell of an atom picks up extra electrons, it is considered a negatively charged ion. Common sources that can cause these electrons to move are friction, chemical energy, mechanical energy, magnetic energy and heat or light (solar) energy.</p>
<p>Conductors such as copper, have many free electrons. Copper contains a single electron on it’s valence shell, and due to it’s distance from the nucleus, it is loosely bound to the atom and is free to move across to other atoms of copper. Conductors contain one, two or three electrons on the outer shell. Insulators on the other hand, contain five to eight electron on the outer shell, and therefore do not easily allow electron movement. Glass is an example of an insulator.  Semiconductors are somewhere inbetween conductors and insulators, allowing for restricted movement. Semiconductors have four electrons on their outer ring, such as silicon.</p>
<p>The unit of electrical charge is called the coulomb. The basic law of charges is that like charges repel, and opposited attract. When two bodies have a difference of electons between them, that means that one has a excess of electrons (negatively charged) and one has a deficiency of electrons (positively charged). This relative electrical charge is called the polarity.</p>
<p><code> Force = Charge 1 x Charge 2 / Distance squared</code></p>
<p>Coulomb’s Law stated that Force in newtons, is equal to the charge on the first body times the charge on the second body, divided by the distance between them squared.  This states that the force or attraction between them is directly related to the product of their charges and inversely related to the distance between them. One coulomb of charge is equal to 6.25×10 to the 18th power, or 6,250,000,000,000,000,000 electrons.</p>
<p>The difference between two points having different charge levels is called a Potential Difference. This is also called Electromotive Force, due to the force moving the electrons from one place to the other. The unit of potential difference, or EMF, is called the Volt. This is merely the force capable of causing electron movement, by it’s difference between two points. Having this difference causes the electrons to move from the negative end to the positive end. The movement of the electrons is known as the Current, and is measured in Amperes, or amps.</p>
<p>One Ampere is a flow of one coulomb of charge for one second. The formula used is current (I) is equal to charge in coulombs (Q) divided by the Time (T) in seconds.</p>
<p>Current flowing through a conductor encounters molecular resistance. This is simply called Resistance (R) and is measured in Ohms. Types of conductor, physical size and length of that conductor, andthe use of semiconductors in the path all cotribute to the resistance of the material or circuit.  An Ohm of resistance is the amount that limits the current to one ampere when on volt of electromotive force is applied.</p>
<p>A Circuit has three parts. There must be a source, a load, and a path for the current to flow. In addition, there may be a switch, or a means to turn the circuit on and off. The voltage source, such as a power supply or battery, provides the means to carry the electricity from the negative to positive points. The path, a conductor such as copper wire, provides a way to transport that electricity to the load, such as a light bulb or resistor.</p>
<p>When a switch is set to the off position, and the circuit is unpowered, this is considered to be an open circuit. Once that switch is turned on, it is considered a closed circuit, one that provides an unbroken path for current to flow.</p>
<p>The techniques of controlling electron flow to acheive a desired result in a circuit is the basis of all electronics.</p>
<?php include("../../footer.php"); ?>
