<!--date=20141027 -->

<?php include("../../headercat.php"); ?>

<h1>Winterizing again: Part 1, The Camper</h1>

<p>It’s getting down to 0 Degrees C again. Time to do my duty and get the camper ready for another long winter. It gets down to -40 C here, so all the water needs to be purged from the system. I found a few cryptic notes from last year and I vowed to not do it again. I’m going to really give it a try and put this down on a page so it’s easier next year.</p>
<p><strong>DRAIN</strong></p>
<p>When I leave the campsite, I give the whole sewer system a good flush and then let it drain out as much as possible. Then pull out the camper and take it home. First, make sure the water pump is off. I get the camper level and open the water plug drain.&nbsp; The drain plug for me is a 1/2″ square PVC plug. Get underneath and let ‘er rip. This should drain the water tank side of your system all the way to the pump. Have a beer. Get more of the stuff out of the camper. Let it drain. No drips? Put the plug back in.</p>
<p>My RV has a basic 5 gallon hot water system with 1/2″ hot water shutoffs on the input and output. I open the shutoffs to the hot water tank. Open the hot water heater cover of your camper and find the drain at the bottom of it, use a wrench and some swearing and take that f’n piece of plastic off and let it drain. I also open each hot water valve in the camper. They will gravity drain themselves for now. Replace the drain plug. Close the hot water valves. Close the hot water shutoffs. That’s it for the tank/pump side for now.</p>
<p><strong>AIR</strong></p>
<p>Next, you need an air compressor to connect it to the the 3/4″ hose water input (hookup water) of your RV. I have 1/4″ fittings on my air compressor. So what I need is a <a href="http://www.princessauto.com/pal/en/Couplers/2-pc-M-Style-Male-Quick-Coupler-Plugs/8057522.p">1/4″ male threaded</a> (air) to 3/4″ female threaded (water hose) fitting. My Co-op had them in the plumbing section. Same threads. If your quick connects for your air compressor at home are bigger (3/8″, 1/2″) then you need those instead, but it’s usually a 3/4″ hose fitting on the water side of the camper. You want to blow all the remaining hookup water out with air, but be careful. Before you connect these, I would be sure to have an <a href="http://www.princessauto.com/pal/en/Air-Preparation/1-4-in-Air-Regulator/8185035.p">air regulator</a> that can regulate the pressure as most air compressors can pump enough PSI to blow out fittings in an RV system. (I am not sure if a RV water regulator works for this and I have not tried.) I have kept the pressure down with the regulator at around 35-45 psi.</p>
<p>Start the air compressor, run inside the camper, open the first cold water tap (I do the camper sink first). once it’s empty and done gurgling, close it, and open the next one (bathroom sink). Continue this (shower, toilet, Etc.) until all the cold water hookups have been blown out.</p>
<p>Open the shutoffs to your hot water tank, and then open the hot water valves one by one. They don’t really empty since the hot water isn’t full (for me, it won’t pump hot water unless the hot water tank is full. Check your setup, you may be able to bypass the hot water tank). Close the hot water shutoffs. Once that is done and there is no more gurgling, The air part is done and I remove the air compressor.</p>
<p><strong>ANTIFREEZE</strong></p>
<p>Unhook the input to the water pump from the tank with a wrench, and either put that hose in the antifreeze jug, or you might need a bit of hose to do this depending on the length of it. Once the antifreeze jug is hooked to the pump input, turn the water pump on. Go around the camper and open up each water valve one by one, Same way as you did before. Once each jug empties, put another one under. Once a valve is running out pink for a few seconds shut it off. This has also put a bit of pink RV antifreeze down the drains. Make sure a decent amount went into the gray water (drains) and the sewer (toilet). I let them both run for a few more seconds just to be sure. So, now the cold water is done.</p>
<p>For the hot water, if you have a bypass you can fill the lines with antifreeze like the cold water, or if you are like me, you have gravity drained down the hot water lines, and aired them out. Options. 1. You are done, or</p>
<p>2. Open the shutoffs and fill the hot water tank a bit with what antifreeze there is left from the pump. It doesn’t fill the hot water lines but they are aired out, and it puts some in the hot water tank.</p>
<p>3. Put the plug back on and fill it with at least 5 gallons more of RV Antifreeze and run the hot water taps till they are full.</p>
<p>I go for #2, and fill some of the tank. RV hot water tanks are pretty expensive in my opinion ($500-$700 CDN in my area). I did this method last year, and had no problems. Now for the long wait until we can go camping again… Next up for winterizing is the boat.</p>

<?php include("../../footer.php"); ?>
